Added links for Gitlab, Compétences and Conférences
aeecleclair/Centralisation pull request #16
Opened 2022-10-03 14:41 UTC by Flavio0834

Added links for Gitlab, Compétences and Conférences as asked in issue  #5. Reused Centrale's logo for Compétences.

Added source link for icons in README.

2022-10-20 09:35 UTC, benjamindenise requested changes

2022-10-20 09:35 UTC, benjamindenise commented on links.yaml
> +    description: Le site des compétences, actuellement en version démo, rencense les évaluations des professeurs et donne accès à un récapitulatif. L'accès nécessite d'être connecté à un réseau inter
"L'accès nécessite d'être connecté au réseau interne de l'école ou au VPN"

2022-10-20 09:35 UTC, benjamindenise commented on links.yaml
> +    description: Le site des conférences permet de retrouver le planning des conférences à venir à l'école, utile pour valider l'UE PRO. L'accès nécessite d'être connecté à un réseau interne à l'écol
Idem

2022-10-20 10:08 UTC, benjamindenise requested changes

2022-10-20 10:38 UTC, armanddidierjean commented on links.yaml
> +    description: Le site des compétences, actuellement en version démo, rencense les évaluations des professeurs et donne accès à un récapitulatif. L'accès nécessite d'être connecté au réseau interne
```suggestion
    description: Le site des compétences, actuellement en version démo, recense les évaluations des professeurs et donne accès à un récapitulatif. L'accès nécessite d'être connecté au réseau interne de l'école ou au VPN.
```

2022-10-21 07:21 UTC, benjamindenise approved these changes

2022-10-27 06:20 UTC, armanddidierjean approved these changes

2022-10-27 06:20 UTC, merged